added daytona sample courier manager
daytonaio/sample-django-courier-manager pull request #1
Opened 2024-12-20 14:00 UTC by rupacesigdel

2024-12-20 14:04 UTC, Tpuljak requested changes

2024-12-20 14:04 UTC, Tpuljak commented on README.md
> +    daytona create https://github.com/rupacesigdel/COURIER_WEB.git
URL is wrong. Should be https://github.com/daytonaio/sample-django-courier-manager

2024-12-21 05:53 UTC, rupacesigdel commented on README.md
> +    daytona create https://github.com/rupacesigdel/COURIER_WEB.git
I  updated it . Please review.

2024-12-21 16:28 UTC, rupacesigdel commented
done


On Fri, Dec 20, 2024 at 7:49 PM Toma Puljak ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In README.md
> <https://github.com/daytonaio/sample-django-courier-manager/pull/1#discussion_r1893979399>
> :
>
> >
> -... MORE STEPS IF NEEDED ...
> +1. **Create the Daytona Environment**:
> +Initialize the project directly with Daytona:
> +  ```sh
> +    daytona create https://github.com/rupacesigdel/COURIER_WEB.git
>
> URL is wrong. Should be
> https://github.com/daytonaio/sample-django-courier-manager
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/daytonaio/sample-django-courier-manager/pull/1#pullrequestreview-2517620292>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BGEB3MAUZXFL4UVLRIITT7T2GQPYVAVCNFSM6AAAAABT7GCRPOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMJXGYZDAMRZGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2024-12-21 16:32 UTC, rupacesigdel commented on README.md
> +    daytona create https://github.com/rupacesigdel/COURIER_WEB.git
@Tpuljak , Did you review it?

2024-12-23 07:31 UTC, merged